@startuml

class Modele{
    Sring nomModele
    int idModele
    Modele()
    Modele(String nomModele)
    Piece getPiece(int idPiece)
    void ajouterPiece(Piece p)
    boolean valider()
}

class Piece{
    String nomPiece
    int idPiece
    Piece(String nomPiece, Modele m)
    Piece(Modele m)
    Mur getMur(int orientation)
    void ajouterMur(Mur m)
    void ajouterPorte(Porte p)
    void retirerPorte(Porte p)
    Porte getPorte(int idPorte)
    boolean valider()
}

class Mur{
    int idMur
    int orientation
    Mur(int orientation)
    void ajouterImage(Image i)
    Image getImage()
    void ajouterPorte(Porte p)
    int getOrientation()

}

class Porte{
    int idPorte
    Porte(Mur a, Rect rectangle)
    void setMurA(Mur mur, Rect rectangle)
    void setMurB(Mur mur, Rect rectangle)
    Mur getMurA()
    Mur getMurB()
    Rect getRectangle(Mur mur)
    void setRectangle(Mur mur, Rect rectangle)
    boolean valider()
}
Modele "1"--"*" Piece
Piece "1"--"4" Mur
Mur "2"--"*" Porte
Mur --"1" Image
Porte --"2" Rect
@enduml